
#define DEW_HEATER_CONTROL_ALWAYS_ON   "ON" 
#define DEW_HEATER_CONTROL_ALWAYS_OFF  "OFF" 
#define DEW_HEATER_CONTROL_TEMPERATURE "TEMPERATURE" 
#define DEW_HEATER_CONTROL_DEWPOINT    "DEW_POINT" 
#define DEW_HEATER_CONTROL_NIGHTIME    "NIGHT" 


#define DEW_HEATER_CONTROL_ENV_VAR       "DEW_HEATER_CONTROL"
#define DEW_HEATER_CONTROL_ENV_VAR_VALUE DEW_HEATER_CONTROL_ALWAYS_OFF

